In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib as plt
import matplotlib.pyplot as plt

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory
# data=pd.read_csv('C:\\Users\\josan\\Documents\\GitHub\\EDEM_MDA2324\\Alumnos\\ES\\Josan_Rodrigo_Cortes\\Dataproject3\\train.csv')
data = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [4]:
# Quitamos los duplicados y comprobamos
data = data.drop_duplicates(keep = False)
data = data.drop_duplicates(keep = False)
data.describe()

age         sex          cp     restecg       label
count  730.000000  730.000000  730.000000  730.000000  730.000000
mean    53.376712    0.791781    3.253425    0.604110    1.135616
std      9.316814    0.406313    0.922301    0.803446    1.257937
min     28.000000    0.000000    1.000000    0.000000    0.000000
25%     47.000000    1.000000    3.000000    0.000000    0.000000
50%     54.000000    1.000000    4.000000    0.000000    1.000000
75%     60.000000    1.000000    4.000000    1.000000    2.000000
max     76.000000    1.000000    4.000000    2.000000    4.000000

In [39]:
import numpy as np

# Reemplazar los valores '?' por NaN
data.replace('?', np.nan, inplace=True)

# Eliminar todas las filas que contienen valores NaN
data.dropna(inplace=True)


In [40]:
data = data.apply(pd.to_numeric, errors='coerce')

In [41]:
data = data.astype(int)

In [42]:
data = data[data >= 0].dropna()


In [43]:
for columna in data.columns:
    valores_unicos = data[columna].unique()
    print(f"Valores únicos en la columna '{columna}': {valores_unicos}")


Valores únicos en la columna 'age': [51 55 44 35 64 56 68 45 43 41 69 66 57 46 67 58 42 49 61 50 59 53 47 62
 54 60 48 70 76 52 63 37 71 34 40 39 65 38 29]
Valores únicos en la columna 'sex': [1 0]
Valores únicos en la columna 'cp': [1 4 2 3]
Valores únicos en la columna 'trestbps': [125 140 120 122 130 104 110 134 160 146 128 108 115 150 170 138 144 180
 100 105 117 192 114 142 148 132 124 152 118 165 172 112 102 135 145 174
 126 154 200 136  94 106 178 164 123]
Valores únicos en la columna 'chol': [213. 217. 169. 192. 246. 256. 211. 208. 303. 177. 233. 172. 235. 409.
 234. 278. 229. 249. 254. 180. 204. 141. 269. 260. 243. 295. 239. 326.
 264. 226. 228. 257. 340. 193. 274. 263. 311. 126. 236. 222. 232. 283.
 258. 212. 240. 214. 201. 164. 198. 230. 188. 197. 253. 318. 245. 313.
 203. 157. 261. 341. 277. 209. 302. 322. 298. 149. 207. 289. 271. 242.
 259. 199. 330. 200. 160. 215. 265. 131. 178. 182. 248. 250. 205. 305.
 206. 244. 184. 216. 282. 342. 225. 185. 262. 267. 218. 294. 220. 276

In [44]:
data.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'label'],
      dtype='object')

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 246 entries, 0 to 731
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       246 non-null    int32  
 1   sex       246 non-null    int32  
 2   cp        246 non-null    int32  
 3   trestbps  246 non-null    int32  
 4   chol      246 non-null    float64
 5   fbs       246 non-null    float64
 6   restecg   246 non-null    int32  
 7   thalach   246 non-null    int32  
 8   exang     246 non-null    int32  
 9   oldpeak   246 non-null    int32  
 10  slope     246 non-null    float64
 11  ca        246 non-null    float64
 12  thal      246 non-null    float64
 13  label     246 non-null    int32  
dtypes: float64(5), int32(9)
memory usage: 20.2 KB


In [46]:
test = pd.read_csv('C:\\Users\\josan\\Documents\\GitHub\\EDEM_MDA2324\\Alumnos\\ES\\Josan_Rodrigo_Cortes\\Dataproject3\\test.csv', delimiter=',', encoding='utf-8')


In [47]:
import numpy as np

# Reemplazar los valores '?' por NaN
test.replace('?', np.nan, inplace=True)

# Eliminar todas las filas que contienen valores NaN
test.dropna(inplace=True)


In [48]:
test = test.apply(pd.to_numeric, errors='coerce')

In [49]:
test = test.astype(int)

In [50]:
test = test[test >= 0].dropna()

In [51]:
for column in test.columns:
    valores_unicostest = test[column].unique()
    print(f"Valores únicos en la columna '{column}': {valores_unicostest}")


Valores únicos en la columna 'age': [51 54 60 62 48 47 39 50 52 59 77 64 57 46 63 44 35 43 65 61 67 55 71 42
 58 45 70 74]
Valores únicos en la columna 'sex': [1 0]
Valores únicos en la columna 'cp': [3 4 2 1]
Valores únicos en la columna 'trestbps': [110. 160. 125. 150. 130. 140. 118. 120. 129. 128. 145. 152. 101. 108.
 105. 138. 115. 158. 112. 132. 155. 156. 135. 170.]
Valores únicos en la columna 'chol': [175. 201. 258. 244. 275. 256. 239. 219. 196. 255. 221. 304. 212. 274.
 197. 267. 407. 204. 183. 226. 268. 303. 248. 166. 206. 192. 237. 305.
 290. 353. 289. 149. 187. 269. 209. 270. 234. 220. 247. 394. 315. 245.
 211. 231. 273. 288.]
Valores únicos en la columna 'fbs': [0 1]
Valores únicos en la columna 'restecg': [0. 2.]
Valores únicos en la columna 'thalach': [123. 163. 141. 154. 139. 149. 160. 118. 140. 158. 161. 164. 162. 132.
  88. 156. 167. 177. 172. 182.  98. 181. 125. 148.  71. 153. 145. 144.
 173. 111. 175. 152. 171. 157. 143. 121. 170. 146. 150. 159.]
Valores únicos en la

In [52]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52 entries, 4 to 182
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       52 non-null     int32  
 1   sex       52 non-null     int32  
 2   cp        52 non-null     int32  
 3   trestbps  52 non-null     float64
 4   chol      52 non-null     float64
 5   fbs       52 non-null     int32  
 6   restecg   52 non-null     float64
 7   thalach   52 non-null     float64
 8   exang     52 non-null     float64
 9   oldpeak   52 non-null     int32  
 10  slope     52 non-null     float64
 11  ca        52 non-null     float64
 12  thal      52 non-null     float64
dtypes: float64(8), int32(5)
memory usage: 4.7 KB


In [53]:
from sklearn.model_selection import train_test_split

# Supongamos que tienes un DataFrame df y deseas dividirlo en conjuntos de entrenamiento y validación
X = data.drop('label', axis=1)  # Features (variables independientes)
y = data['label']  # Variable objetivo (variable dependiente)

# Dividir el DataFrame en conjuntos de entrenamiento y validación
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.15, random_state=42)

# test_size=0.2 indica que el 20% de los datos se utilizarán para validación
# random_state=42 establece una semilla aleatoria para reproducibilidad


In [54]:
from sklearn.neighbors import KNeighborsClassifier

# Crear un clasificador k-NN
knn = KNeighborsClassifier(n_neighbors=5)  # Define el número de vecinos, puedes ajustarlo según sea necesario

# Entrenar el clasificador con los datos de entrenamiento
knn.fit(X_train, y_train)

# Hacer predicciones en los datos de validación
y_pred = knn.predict(X_val)
from sklearn.metrics import accuracy_score, confusion_matrix

# Calcular la precisión del modelo
precisionknn = accuracy_score(y_val, y_pred)
print("Precisión del modelo:", precisionknn)

# Calcular la matriz de confusión
matriz_confusionknn = confusion_matrix(y_val, y_pred)
print("Matriz de confusión:")
print(matriz_confusionknn)

Precisión del modelo: 0.5405405405405406
Matriz de confusión:
[[19  1  1  0  0]
 [ 5  0  0  0  0]
 [ 3  0  1  0  0]
 [ 4  1  1  0  0]
 [ 0  1  0  0  0]]


In [72]:
from sklearn.ensemble import RandomForestClassifier

# Crear un clasificador Random Forest
random_forest = RandomForestClassifier(n_estimators=100, random_state=42)  # Puedes ajustar el número de árboles (n_estimators)

# Entrenar el clasificador con los datos de entrenamiento
random_forest.fit(X_train, y_train)

# Hacer predicciones en los datos de validación
y_pred_rf = random_forest.predict(X_val)



# Calcular la precisión del modelo
precisionrf = accuracy_score(y_val, y_pred_rf)
print("Precisión del modelo:", precisionrf)

# Calcular la matriz de confusión
matriz_confusionrf = confusion_matrix(y_val, y_pred_rf)
print("Matriz de confusión:")
print(matriz_confusionrf)


Precisión del modelo: 0.6486486486486487
Matriz de confusión:
[[21  0  0  0  0]
 [ 3  0  0  2  0]
 [ 1  1  2  0  0]
 [ 3  0  2  1  0]
 [ 1  0  0  0  0]]


In [70]:
from sklearn.naive_bayes import GaussianNB

# Crear un clasificador Naive Bayes
naive_bayes = GaussianNB()

# Entrenar el clasificador con los datos de entrenamiento
naive_bayes.fit(X_train, y_train)

# Hacer predicciones en los datos de validación
y_pred_nb = naive_bayes.predict(X_val)

# Calcular la precisión del modelo
precisionnb = accuracy_score(y_val, y_pred_nb)
print("Precisión del modelo:", precisionnb)

# Calcular la matriz de confusión
matriz_confusionnb = confusion_matrix(y_val, y_pred_nb)
print("Matriz de confusión:")
print(matriz_confusionnb)


Precisión del modelo: 0.5675675675675675
Matriz de confusión:
[[18  3  0  0  0]
 [ 2  2  0  1  0]
 [ 0  2  0  1  1]
 [ 0  3  2  1  0]
 [ 0  1  0  0  0]]


In [69]:
from sklearn.ensemble import GradientBoostingClassifier

# Crear un clasificador Gradient Boosting
gradient_boosting = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)  
# Puedes ajustar el número de árboles (n_estimators) y la tasa de aprendizaje (learning_rate)

# Entrenar el clasificador con los datos de entrenamiento
gradient_boosting.fit(X_train, y_train)

# Hacer predicciones en los datos de validación
y_pred_gb = gradient_boosting.predict(X_val)

precisiongb = accuracy_score(y_val, y_pred_gb)
print("Precisión del modelo:", precisiongb)

# Calcular la matriz de confusión
matriz_confusionnb = confusion_matrix(y_val, y_pred_gb)
print("Matriz de confusión:")
print(matriz_confusionnb)


Precisión del modelo: 0.6486486486486487
Matriz de confusión:
[[18  2  1  0  0]
 [ 2  2  0  1  0]
 [ 0  1  3  0  0]
 [ 3  1  1  1  0]
 [ 0  1  0  0  0]]


In [68]:
from sklearn.linear_model import LogisticRegression

# Crear un clasificador de regresión logística
logistic_regression = LogisticRegression(random_state=42)  

# Entrenar el clasificador con los datos de entrenamiento
logistic_regression.fit(X_train, y_train)

# Hacer predicciones en los datos de validación
y_pred_lr = logistic_regression.predict(X_val)

precisionrl = accuracy_score(y_val, y_pred_lr)
print("Precisión del modelo:", precisionrl)

# Calcular la matriz de confusión
matriz_confusionrl = confusion_matrix(y_val, y_pred_lr)
print("Matriz de confusión:")
print(matriz_confusionrl)


Precisión del modelo: 0.5675675675675675
Matriz de confusión:
[[18  2  1  0  0]
 [ 2  2  0  1  0]
 [ 0  3  0  1  0]
 [ 2  2  1  1  0]
 [ 0  1  0  0  0]]


C:\Users\josan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [67]:
from sklearn.svm import SVC

# Crear un clasificador SVM
svm_classifier = SVC(kernel='linear', random_state=42)  # Kernel lineal, puedes cambiarlo según sea necesario

# Entrenar el clasificador con los datos de entrenamiento
svm_classifier.fit(X_train, y_train)

# Hacer predicciones en los datos de validación
y_pred_svm = svm_classifier.predict(X_val)

precisionsvm = accuracy_score(y_val, y_pred_svm)
print("Precisión del modelo:", precisionsvm)

# Calcular la matriz de confusión
matriz_confusionsvm = confusion_matrix(y_val, y_pred_svm)
print("Matriz de confusión:")
print(matriz_confusionsvm)


Precisión del modelo: 0.5945945945945946
Matriz de confusión:
[[20  1  0  0  0]
 [ 3  1  0  1  0]
 [ 0  2  0  1  1]
 [ 2  1  2  1  0]
 [ 1  0  0  0  0]]
